### ISSUE TITLE
2022/03/30 django with multi-staged building docker

### ISSUE THREAD

**Issue by Lootmann** [Lootmann/LearningGuide#44]
- [x] Dockerfile
- [x] compose.yml
- [x] multi-staged build 
- [x] django-environ
- [x] psycopg2-binary (prebuiled)
- [x] config/settings.py
- [x] Makefile
  
~~- [ ] automation .env create~~
    ~~- [ ] POSTGRES credentials~~

**Comment by Lootmann** [comment]
read and config `python:3.10` dicker image
from Docker Hub

**Comment by Lootmann** [comment]
create env sh

**Comment by Lootmann** [comment]
use docker compose v2

**Comment by Lootmann** [comment]
## Dockerfile


```dockerfile
# building
FROM python:3.10-buster as builder

RUN apt-get update \
  && apt-get clean all \
  && rm -rf ~/.cache \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /code
WORKDIR /code

COPY ./requirements/docker.txt /code/

RUN pip3 install -U pip && pip3 install -r ./docker.txt

# deploy
FROM python:3.10-slim-buster as runner

ENV PYTHONUNBUFFERD 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages

WORKDIR /code
COPY . /code/

CMD ["./wait.sh", "db", "python3.10", "/code/manage.py",  "runserver"]
```

## compose.yml

```yaml
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - type: bind
        source: .
        target: /code
    ports:
      - 8000:8000
    depends_on:
      - db
    tty: true

  db:
    image: postgres:14
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-db:
```


```sh
#!/bin/bash
# wait-for-postgres.sh

set -e

host="$1"
shift
cmd="$@"

until psql -h "$host" -U "postgres" -c '\l'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up - executing command"
exec $cmd
```


## .env

```
SECRET_KEY=insecure-django-secret-ket
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1

DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
```

**Comment by Lootmann** [comment]
# compose.yml

```yaml
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - type: bind
        source: .
        target: /code
    ports:
      - 8000:8000
    depends_on:
      - db
    tty: true

  db:
    image: postgres:14
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-db:
```
